import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SPN RAO
 */
public class Faculty_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Faculty_Dashboard
     */
    public String userid="";
    public Faculty_Dashboard() {
        initComponents();
        this.setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("img\\mmmutlogo-64.png"));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    Faculty_Dashboard(String text) {
        userid=text;
        initComponents();
        this.setVisible(true);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage("img\\mmmutlogo-64.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nav_pane = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        add_mark = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        centre = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        welcome_text = new javax.swing.JLabel();
        welcome_logo = new javax.swing.JLabel();
        change_password = new javax.swing.JLabel();
        add_mark_form = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        courseOption = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        branchOption = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        change_password_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faculty");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav_pane.setBackground(new java.awt.Color(51, 204, 255));
        nav_pane.setPreferredSize(new java.awt.Dimension(180, 700));
        nav_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-solid-60.png"))); // NOI18N
        logo.setText("Faculty");
        nav_pane.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, -1));

        add_mark.setBackground(new java.awt.Color(51, 204, 255));
        add_mark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_mark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_markMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_markMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_markMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-user-128-.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Add Student Mark");

        javax.swing.GroupLayout add_markLayout = new javax.swing.GroupLayout(add_mark);
        add_mark.setLayout(add_markLayout);
        add_markLayout.setHorizontalGroup(
            add_markLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_markLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(add_markLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        add_markLayout.setVerticalGroup(
            add_markLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_markLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nav_pane.add(add_mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, 180));

        getContentPane().add(nav_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.setBackground(new java.awt.Color(51, 255, 153));
        header.setPreferredSize(new java.awt.Dimension(1020, 40));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-circle-regular-24.png"))); // NOI18N
        user.setText(userid);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        header.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 5, 130, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-regular-24.png"))); // NOI18N
        logout.setToolTipText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        header.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 40));

        centre.setLayout(new java.awt.CardLayout());

        Welcome.setPreferredSize(new java.awt.Dimension(1020, 660));

        welcome_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcome_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_text.setText("Welcome");

        welcome_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teacher-128.png"))); // NOI18N

        change_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        change_password.setText("Change Password");
        change_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_passwordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(welcome_text, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(welcome_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(change_password)
                .addGap(24, 24, 24))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(welcome_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(change_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        centre.add(Welcome, "card2");

        add_mark_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add_mark_form.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 1000, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Add Marks");
        add_mark_form.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 41, 130, 27));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Select Course : ");
        add_mark_form.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, 27));

        courseOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Course--", "B. Tech", "M. Tech", "Phd" }));
        courseOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseOptionItemStateChanged(evt);
            }
        });
        add_mark_form.add(courseOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 118, 115, 27));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Select Branch : ");
        add_mark_form.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 117, -1, 27));

        branchOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Branch--" }));
        add_mark_form.add(branchOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 118, 115, 27));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add_mark_form.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 69, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No.", "Mark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add_mark_form.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 370));

        save.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        add_mark_form.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, -1, 27));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Year ");
        add_mark_form.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 118, 40, 27));
        add_mark_form.add(yearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 118, 60, 27));

        centre.add(add_mark_form, "card3");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Change Password");

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("Old Password");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setText("New Password");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel26.setText("Confirm Password");

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jPasswordField3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButton4.setBackground(new java.awt.Color(51, 255, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout change_password_panelLayout = new javax.swing.GroupLayout(change_password_panel);
        change_password_panel.setLayout(change_password_panelLayout);
        change_password_panelLayout.setHorizontalGroup(
            change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_password_panelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, change_password_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18))
            .addGroup(change_password_panelLayout.createSequentialGroup()
                .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(change_password_panelLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(change_password_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(change_password_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(change_password_panelLayout.createSequentialGroup()
                                    .addGap(151, 151, 151)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(change_password_panelLayout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        change_password_panelLayout.setVerticalGroup(
            change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(change_password_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(change_password_panelLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(change_password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        centre.add(change_password_panel, "card6");

        getContentPane().add(centre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 1020, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_markMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_markMouseClicked
        handleCentre(1);
        onClick(add_mark);
        jScrollPane1.setVisible(false);
        save.setVisible(false);
    }//GEN-LAST:event_add_markMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        onLeave(add_mark);
    }//GEN-LAST:event_userMouseClicked

    private void courseOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseOptionItemStateChanged
        if(courseOption.getSelectedIndex()==1)
        {
            branchOption.removeAllItems();
            branchOption.addItem("--Select Branch--");
            branchOption.addItem("Computer Science");
            branchOption.addItem("Information Technology");
            branchOption.addItem("Civil Engineering");
            branchOption.addItem("Electronics and Communication Engineering");
            branchOption.addItem("Electrical Engineering");
            branchOption.addItem("Mechanical Engineering");
        }
        else if (courseOption.getSelectedIndex()==2)
        {
            branchOption.removeAllItems();
            branchOption.addItem("--Select Branch--");
            branchOption.addItem("VLSI");
            branchOption.addItem("Seismology");
        }
        else if(courseOption.getSelectedIndex()==3)
        {
            branchOption.removeAllItems();
            branchOption.addItem("--Select Branch--");
            branchOption.addItem("Maths");
            branchOption.addItem("Physics");
        }
        else
        {
            branchOption.removeAllItems();
            branchOption.addItem("--Select Branch--");
        }
    }//GEN-LAST:event_courseOptionItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.table.DefaultTableModel model =(javax.swing.table.DefaultTableModel)jTable1.getModel();
        for(int i=jTable1.getRowCount()-1;i>=0;i--)
            model.removeRow(i);
        jScrollPane1.setVisible(true);
        if(!(courseOption.getSelectedIndex()==0&&branchOption.getSelectedIndex()==0&&yearField.getText().trim().equals("")))
        {
            String query= "select roll from students where course = ? and branch =? and yod = ?";
            connectionManager cm = new connectionManager();
            
            try
            {
                cm.connect();
                cm.pstmt=cm.conn.prepareStatement(query);
                cm.pstmt.setString(1,courseOption.getSelectedItem().toString());
                cm.pstmt.setString(2,branchOption.getSelectedItem().toString());
                cm.pstmt.setInt(3,Integer.parseInt(yearField.getText().trim()));
                cm.rs=cm.pstmt.executeQuery();
                while(cm.rs.next())
                {
                    model.addRow(new Object[]{cm.rs.getInt(1),""});
                }
                save.setVisible(true);
            }
            catch(java.sql.SQLException e)
            {
                 javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                try {
                    cm.rs.close();
                    cm.pstmt.close();
                    cm.conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Faculty_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
            javax.swing.JOptionPane.showMessageDialog(null, "one or more fields are empty", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        change_password_panel.setVisible(false);
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");
        Welcome.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jPasswordField1.getText().trim().equals("")||jPasswordField2.getText().trim().equals("")||jPasswordField3.getText().trim().equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(null,"one or more fields are empty","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String oldpass,newpass,cnfrmpass;
            oldpass=new String(jPasswordField1.getPassword());
            newpass=new String(jPasswordField2.getPassword());
            cnfrmpass=new String(jPasswordField3.getPassword());
            try
            {
                connectionManager.connect();
                String query="select pass from faculty where id=?";
                connectionManager.pstmt=connectionManager.conn.prepareStatement(query);
                connectionManager.pstmt.setInt(1,Integer.parseInt(user.getText()));
                connectionManager.rs=connectionManager.pstmt.executeQuery();
                if(connectionManager.rs.next())
                {
                    if(oldpass.equals(connectionManager.rs.getString(1))&&newpass.equals(cnfrmpass))
                    {
                        query="update faculty set pass=? where id =?";
                        connectionManager.pstmt=connectionManager.conn.prepareStatement(query);
                        connectionManager.pstmt.setString(1,newpass);
                        connectionManager.pstmt.setString(2,user.getText());
                        int n=connectionManager.pstmt.executeUpdate();
                        if(n!=0)
                        javax.swing.JOptionPane.showMessageDialog(null,"Password Changed!","Success",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        query="update users set pass=? where name=?";
                        connectionManager.pstmt=connectionManager.conn.prepareStatement(query);
                        connectionManager.pstmt.setString(1,newpass);
                        connectionManager.pstmt.setString(2,user.getText());
                        connectionManager.pstmt.executeUpdate();
                        jPasswordField1.setText("");
                        jPasswordField2.setText("");
                        jPasswordField3.setText("");
                        Welcome.setVisible(true);
                        change_password_panel.setVisible(false);
                    }
                    else
                    javax.swing.JOptionPane.showMessageDialog(null,"Either old password incorrect or New password doesn't match the confirm password","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(java.sql.SQLException e)
            {
                javax.swing.JOptionPane.showMessageDialog(null,e.getMessage(),"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                try {
                    connectionManager.rs.close();
                    connectionManager.pstmt.close();
                    connectionManager.conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Student_dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        model =(javax.swing.table.DefaultTableModel)jTable1.getModel();
        connectionManager cm =new connectionManager();
        cm.connect();
        int k=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            try
            {
                String rolln=jTable1.getValueAt(i, 0).toString();
                String mark=(jTable1.getValueAt(i, 1).toString());
                String subj;
                cm.pstmt=cm.conn.prepareStatement("select subject from subjects where fac_id=?");
                cm.pstmt.setString(1,userid);
                cm.rs=cm.pstmt.executeQuery();
                ResultSet rs;
                while(cm.rs.next())
                {
                    subj=cm.rs.getString(1);
                    cm.pstmt=cm.conn.prepareStatement("select major1,major2,major3,minor1,minor2 from student_subjects where roll=?");
                    cm.pstmt.setString(1,rolln);
                    rs=cm.pstmt.executeQuery();
                    if(rs.next())
                    {
                        if(subj.equalsIgnoreCase(rs.getString(1)))
                            k=1;
                        else if (subj.equalsIgnoreCase(rs.getString(2)))
                            k=2;
                        else if(subj.equalsIgnoreCase(rs.getString(3)))
                            k=3;
                        else if(subj.equalsIgnoreCase(rs.getString(4)))
                            k=4;
                        else if(subj.equalsIgnoreCase(rs.getString(5)))
                            k=5;
                        else k=0;
                    }
                    else
                        System.out.println("Empty ResultSet");
                }
                System.out.println("k="+k);
                if(k==1)
                {
                    cm.pstmt=cm.conn.prepareStatement("select roll from student_marks where roll=?");
                    cm.pstmt.setString(1, rolln);
                    rs=cm.pstmt.executeQuery();
                    if(rs.next())
                    {
                        cm.pstmt=cm.conn.prepareStatement("update student_marks set major1=? where roll=?");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                    else
                    {
                        cm.pstmt=cm.conn.prepareStatement("insert into student_marks (major1,roll) values(?,?)");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                }
                else if(k==2)
                {
                    cm.pstmt=cm.conn.prepareStatement("select roll from student_marks where roll=?");
                    cm.pstmt.setString(1, rolln);
                    rs=cm.pstmt.executeQuery();
                    if(rs.next())
                    {
                        cm.pstmt=cm.conn.prepareStatement("update student_marks set major2=? where roll=?");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                    else
                    {
                        cm.pstmt=cm.conn.prepareStatement("insert into student_marks (major2,roll) values(?,?)");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                }
                else if(k==3)
                {
                    cm.pstmt=cm.conn.prepareStatement("select roll from student_marks where roll=?");
                    cm.pstmt.setString(1, rolln);
                    rs=cm.pstmt.executeQuery();
                    if(rs.next())
                    {
                        cm.pstmt=cm.conn.prepareStatement("update student_marks set major3=? where roll=?");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                    else
                    {
                        cm.pstmt=cm.conn.prepareStatement("insert into student_marks (major3,roll) values(?,?)");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                }
                else if(k==4)
                {
                    cm.pstmt=cm.conn.prepareStatement("select roll from student_marks where roll=?");
                    cm.pstmt.setString(1, rolln);
                    rs=cm.pstmt.executeQuery();
                    if(rs.next())
                    {
                        cm.pstmt=cm.conn.prepareStatement("update student_marks set minor1=? where roll=?");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                    else
                    {
                        cm.pstmt=cm.conn.prepareStatement("insert into student_marks (mminor1,roll) values(?,?)");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                }
                else if(k==5)
                {
                    cm.pstmt=cm.conn.prepareStatement("select roll from student_marks where roll=?");
                    cm.pstmt.setString(1, rolln);
                    rs=cm.pstmt.executeQuery();
                    if(rs.next())
                    {
                        cm.pstmt=cm.conn.prepareStatement("update student_marks set minor2=? where roll=?");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                    else
                    {
                        cm.pstmt=cm.conn.prepareStatement("insert into student_marks (minor2,roll) values(?,?)");
                        cm.pstmt.setString(1,mark);
                        cm.pstmt.setString(2,rolln);
                        cm.pstmt.executeUpdate();
                    }
                }
                else
                    javax.swing.JOptionPane.showMessageDialog(null,"Your subjects are not opted by pupil"+" "+(i+1),"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            catch (SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Data Added", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        jScrollPane1.setVisible(false);
        courseOption.setSelectedIndex(0);
        branchOption.setSelectedIndex(0);
        yearField.setText("");
        save.setVisible(false);
    }//GEN-LAST:event_saveActionPerformed

    private void change_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_passwordMouseClicked
        Welcome.setVisible(false);
        change_password_panel.setVisible(true);
    }//GEN-LAST:event_change_passwordMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        login lg=new login();
        lg.setVisible(true);
        try
        {
            connectionManager.pstmt.close();
            connectionManager.rs.close();
            connectionManager.conn.close();
        }
        catch(java.sql.SQLException e)
        {
            System.out.println(e.getMessage());
        }
        catch(NullPointerException ne)
        {
            System.out.println(ne.getMessage());
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void add_markMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_markMouseEntered
        add_mark.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_add_markMouseEntered

    private void add_markMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_markMouseExited
        if(add_mark_form.isVisible())
            add_mark.setBackground(new java.awt.Color(240,240,240));
        else
            add_mark.setBackground(new java.awt.Color(51,204,255));
    }//GEN-LAST:event_add_markMouseExited

    private void handleCentre(int arg)
    {
        switch(arg)
        {
            case 0: Welcome.setVisible(true);
                    add_mark_form.setVisible(false);
                    break;
            default : Welcome.setVisible(false);
                    add_mark_form.setVisible(true);
        }
    }
    private void onClick(javax.swing.JPanel p1)
    {
        p1.setBackground(new java.awt.Color(240,240,240));
    }
    private void onLeave(javax.swing.JPanel p1)
    {
        p1.setBackground(new java.awt.Color(51,204,255));
    }
    
    private javax.swing.table.DefaultTableModel model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Welcome;
    private javax.swing.JPanel add_mark;
    private javax.swing.JPanel add_mark_form;
    private javax.swing.JComboBox<String> branchOption;
    private javax.swing.JPanel centre;
    private javax.swing.JLabel change_password;
    private javax.swing.JPanel change_password_panel;
    private javax.swing.JComboBox<String> courseOption;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel nav_pane;
    private javax.swing.JButton save;
    private javax.swing.JLabel user;
    private javax.swing.JLabel welcome_logo;
    private javax.swing.JLabel welcome_text;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
